package com.wal.ai;
import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.Typeface;import android.view.*;import android.widget.*;import android.text.*;import java.io.*;import java.net.*;import java.util.*;import org.json.*;
public class MainActivity extends Activity{
 LinearLayout root,content; TextView state; JSONArray tickers;
 int d(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.rgb(25,35,55));v.setPadding(d(12),d(8),d(12),d(8));return v;}
 public void onCreate(Bundle b){super.onCreate(b);ui();refresh();}
 void ui(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(246,250,253));
  LinearLayout head=new LinearLayout(this);head.setPadding(d(16),d(12),d(16),d(10));head.setGravity(Gravity.CENTER_VERTICAL);head.setBackgroundColor(Color.WHITE);
  TextView w=t("W",24);w.setGravity(17);w.setTextColor(Color.WHITE);w.setTypeface(null,Typeface.BOLD);w.setBackgroundColor(Color.rgb(86,102,240));head.addView(w,new LinearLayout.LayoutParams(d(46),d(46)));
  LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.addView(t("WAL",21));b.addView(t("Whale Analysis Live",10));head.addView(b,new LinearLayout.LayoutParams(0,-2,1));
  state=t("● CONNECTING",11);state.setTextColor(Color.rgb(20,150,100));head.addView(state);root.addView(head);
  ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(d(14),d(18),d(14),d(30));
  TextView h=t("WAL Intelligence",29);h.setTypeface(null,Typeface.BOLD);content.addView(h);content.addView(t("Real data • explainable signals • no fabricated whales",13));
  EditText q=new EditText(this);q.setHint("WAL Search AI — name / symbol / contract");q.setSingleLine();q.setBackgroundColor(Color.WHITE);content.addView(q,new LinearLayout.LayoutParams(-1,d(56)));
  Button radar=new Button(this);radar.setText("WHALE RADAR  •  SCAN 100+ CANDIDATES");content.addView(radar);
  radar.setOnClickListener(v->showWhaleInfo());
  LinearLayout tabs=new LinearLayout(this);String[] names={"MARKETS","SIGNALS","WHALE RADAR","INTELLIGENCE"};for(String n:names){Button x=new Button(this);x.setText(n);tabs.addView(x,new LinearLayout.LayoutParams(0,d(52),1));if(n.equals("WHALE RADAR"))x.setOnClickListener(v->showWhaleInfo());}content.addView(tabs);
  LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);
  q.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int e){}public void afterTextChanged(Editable e){}public void onTextChanged(CharSequence s,int a,int b,int c){render(list,s.toString());}});
  sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);render(list,"");
 }
 void refresh(){new Thread(()->{try{URL u=new URL("https://api.binance.com/api/v3/ticker/24hr");HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(12000);c.setReadTimeout(12000);BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder s=new StringBuilder();String z;while((z=r.readLine())!=null)s.append(z);tickers=new JSONArray(s.toString());runOnUiThread(()->{state.setText("● LIVE");render(findList(),"");});}catch(Exception e){runOnUiThread(()->state.setText("● OFFLINE — LAST DATA UNAVAILABLE"));}}).start();}
 LinearLayout findList(){return (LinearLayout)((LinearLayout)content).getChildAt(content.getChildCount()-1);}
 void render(LinearLayout list,String query){if(tickers==null)return;list.removeAllViews();String q=query.toUpperCase();int n=0;for(int i=0;i<tickers.length()&&n<60;i++)try{JSONObject o=tickers.getJSONObject(i);String s=o.getString("symbol");if(!s.endsWith("USDT")||(!q.isEmpty()&&!s.contains(q)))continue;double p=o.getDouble("lastPrice"),c=o.getDouble("priceChangePercent");LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(d(12),d(10),d(12),d(10));card.setBackgroundColor(Color.WHITE);TextView a=t(s.replace("USDT","")+"   $"+String.format(Locale.US,"%.6f",p),18);a.setTypeface(null,Typeface.BOLD);TextView x=t("24h "+String.format(Locale.US,"%.2f%%",c)+"   •   SIGNAL: WAIT",12);x.setTextColor(c>=0?Color.rgb(10,150,95):Color.rgb(205,55,75));TextView y=t("Evidence: INSUFFICIENT DATA  |  Data Quality: LIVE MARKET",11);card.addView(a);card.addView(x);card.addView(y);list.addView(card,new LinearLayout.LayoutParams(-1,d(92)));Space sp=new Space(this);list.addView(sp,new LinearLayout.LayoutParams(1,d(7)));n++;}catch(Exception ignored){}}
 void showWhaleInfo(){new AlertDialog.Builder(this).setTitle("WAL Whale Radar").setMessage("Production rule:\n\n• Inspect up to 100+ candidate wallets per asset when available.\n• Exclude exchanges, LP/DEX, staking, bridges, contracts, treasury and known bots.\n• Unknown wallets remain UNVERIFIED.\n• No fabricated whale data.\n\nCurrent Android build has live market connectivity. Full multi-chain wallet indexing requires backend/provider credentials and RPC/indexer access; without them WAL reports INSUFFICIENT DATA rather than inventing whales.").setPositiveButton("OK",null).show();}
}