package com.wal.ai;

import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.Typeface;import android.view.*;import android.widget.*;import android.text.*;import java.io.*;import java.net.*;import org.json.*;

public class MainActivity extends Activity {
  LinearLayout root,list; TextView status; JSONArray marketData;
  int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
  TextView tv(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(Color.rgb(23,32,51));t.setPadding(dp(12),dp(8),dp(12),dp(8));return t;}
  public void onCreate(Bundle b){super.onCreate(b);build();loadMarkets();}
  void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(245,249,253));LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(16),dp(12),dp(16),dp(12));bar.setBackgroundColor(Color.WHITE);TextView logo=tv("W",24);logo.setTextColor(Color.WHITE);logo.setGravity(17);logo.setTypeface(null,Typeface.BOLD);logo.setBackgroundColor(Color.rgb(91,108,255));bar.addView(logo,new LinearLayout.LayoutParams(dp(46),dp(46)));LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);TextView n=tv("WAL",21);n.setTypeface(null,Typeface.BOLD);brand.addView(n);brand.addView(tv("Whale Analysis Live",10));bar.addView(brand,new LinearLayout.LayoutParams(0,-2,1));status=tv("● CONNECTING…",12);status.setTextColor(Color.rgb(10,156,96));bar.addView(status);root.addView(bar);ScrollView sv=new ScrollView(this);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(20),dp(16),dp(30));TextView h=tv("Whale Intelligence",30);h.setTypeface(null,Typeface.BOLD);body.addView(h);body.addView(tv("Real market data • no fabricated prices",14));EditText search=new EditText(this);search.setHint("WAL SEARCH AI — BTC, ETH, SOL…");search.setSingleLine(true);search.setBackgroundColor(Color.WHITE);body.addView(search,new LinearLayout.LayoutParams(-1,dp(58)));list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);body.addView(list);body.addView(tv("Whale verification: independently verified on-chain data only. Missing data = INSUFFICIENT DATA.",13));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){render(s.toString());}public void afterTextChanged(Editable e){}});}
  void loadMarkets(){new Thread(()->{try{URL u=new URL("https://api.binance.com/api/v3/ticker/24hr");HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(10000);c.setReadTimeout(10000);BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder x=new StringBuilder();String z;while((z=r.readLine())!=null)x.append(z);marketData=new JSONArray(x.toString());runOnUiThread(()->{status.setText("● LIVE DATA");render("");});}catch(Exception e){runOnUiThread(()->status.setText("● OFFLINE"));}}).start();}
  void render(String q){if(marketData==null)return;list.removeAllViews();int count=0;String qq=q.toUpperCase();for(int i=0;i<marketData.length()&&count<30;i++){try{JSONObject o=marketData.getJSONObject(i);String s=o.getString("symbol");if(!s.endsWith("USDT")||(!qq.isEmpty()&&!s.contains(qq)))continue;double p=o.getDouble("lastPrice"),chg=o.getDouble("priceChangePercent");LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(14),dp(12),dp(14),dp(12));row.setBackgroundColor(Color.WHITE);TextView a=tv(s.replace("USDT","")+"   $"+String.format("%.6f",p),18);a.setTypeface(null,Typeface.BOLD);TextView b=tv("24h: "+String.format("%.2f%%",chg)+"   Signal: WAIT   Evidence: INSUFFICIENT DATA",12);b.setTextColor(chg>=0?Color.rgb(10,156,96):Color.rgb(198,46,69));row.addView(a);row.addView(b);list.addView(row,new LinearLayout.LayoutParams(-1,dp(88)));Space sp=new Space(this);list.addView(sp,new LinearLayout.LayoutParams(1,dp(8)));count++;}catch(Exception ignored){}}}
}
